#!/bin/bash

PROMTAIL_VERSION="2.9.1"
PROMTAIL_SHA256="462365252e62640619b798c95a3ae35f71a795150b95b2e2c9549054e65ff200"
PROMTAIL_PATH="https://github.com/grafana/loki/releases/download/v${PROMTAIL_VERSION}/promtail_${PROMTAIL_VERSION}_amd64.deb"

if ! promtail --version | grep -q "$PROMTAIL_VERSION"; then
    download_and_verify $PROMTAIL_PATH $PROMTAIL_SHA256 "promtail_${PROMTAIL_VERSION}_amd64.deb"
    dpkg -i "$TMPDIR/cache/promtail_${PROMTAIL_VERSION}_amd64.deb"
fi

mkdir -p /var/lib/promtail/
chown promtail:nogroup /var/lib/promtail

echo -e "[Service]\nTimeoutSec = 2" > /etc/systemd/system/promtail.service.d/override.conf
cat << EOF > /etc/promtail/promtail.yml
server:
  disable: true
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: ${LOKI_URL}

scrape_configs:
  - job_name: journal
    journal:
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        regex: "snap.immich-distribution.*"
        action: keep

      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
  - job_name: system
    static_configs:
      - targets:
        - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
EOF

systemctl daemon-reload
systemctl enable --now promtail
